--local theme_config = require("config.theme")
--
--return {
--  {
--  "ellisonleao/gruvbox.nvim",
--  name = "gruvbox",
--  lazy = false,
--  priority = 1000,
--  config = function()
--    require("gruvbox").setup({})
--    vim.cmd.colorscheme("gruvbox")
--  end,
--  },
--
--}
