# vim:ft=kitty

## name: Gruvbox Dark


background #272e33
foreground #d3c6aa
selection_background #d3c6aa
selection_foreground #272e33
url_color #7fbbb3
cursor #d3c6aa
cursor_text_color background

# normal
color0 #7a8478
color1 #e67e80
color2 #a7c080
color3 #dbbc7f
color4 #7fbbb3
color5 #d699b6
color6 #83c092
color7 #9da9a0

# bright
color8  #7a8478
color9  #e67e80
color10 #a7c080
color11 #dbbc7f
color12 #7fbbb3
color13 #d699b6
color14 #83c092
color15 #9da9a0

